[project]
name = "datanode-opt"
version = "0.1.0"
description = "Experiment on Spark with different number of hadoop datanodes"
requires-python = ">=3.12"
dependencies = [
    "pre-commit",
    "numpy <2.0.0",
    "pyspark",
    "kagglehub",
    "pandas"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
