[project]
name = "lakehouse-toy"
version = "0.1.0"
description = "Experiments with toy lakehouse"
requires-python = ">=3.12"
dependencies = [
    "pre-commit",
    "numpy <2.0.0",
    "pyspark==3.5.0",
    "kagglehub",
    "pandas",
    "matplotlib",
    "seaborn",
    "delta-spark==3.2.0",
    "mlflow"
]

[tool.hatch.build.targets.wheel]
packages = ["src"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
